# .pre-commit-config.yaml
# See https://pre-commit.com/ for usage and config

ci:
  skip: [update-nvim]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua-github
        name: stylua
        entry: stylua nvim_lua/.config/nvim/
        pass_filenames: false

  - repo: https://github.com/spinergie/pre-commit-dprint
    rev: v0.45.0
    hooks:
      - id: dprint
        entry: dprint fmt --incremental=false --allow-no-files
        pass_filenames: false

  - repo: local
    hooks:
      - id: update-nvim
        name: Update nvim README
        language: script
        pass_filenames: false
        entry: .update-nvim
