# .pre-commit-config.yaml
# See https://pre-commit.com/ for usage and config

ci:
    skip: [update-nvim]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: local
    hooks:
      - id: update-nvim
        name: Update nvim README
        language: script
        pass_filenames: false
        entry: .update-nvim

      - id: dprint
        name: dprint
        entry: dprint fmt --incremental=false --allow-no-files
        language: node
        pass_filenames: false
        additional_dependencies: ["dprint"]

      - id: stylua
        name: stylua
        entry: stylua nvim_lua/.config/nvim/
        language: system
        pass_filenames: false
