theme = "gruvbox_dark_soft"

[editor]
auto-completion = true
bufferline = "always"
cursorline = true
cursorcolumn = true
line-number = "relative"
mouse = true
auto-save = false
text-width = 88
soft-wrap = { enable = true, wrap-at-text-width = true, wrap-indicator = "" }
rulers = [88]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "file-name", "spacer", "diagnostics"]
right = [
  "position",
  "separator",
  "spacer",
  "position-percentage",
  "spacer",
  "separator",
  "total-line-numbers",
  "separator",
  "file-line-ending",
  "separator",
  "file-type",
]

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[keys.normal.space.h]
r = ":reset-diff-change"

[keys.normal.space.space]
s = ":format"
w = ":reflow"

[keys.normal]
D = "kill_to_line_end"
"-" = "file_picker_in_current_buffer_directory"
