theme = "gruvbox_dark_soft"

[editor]
auto-completion = true
bufferline = "always"
cursorline = true
cursorcolumn = true
line-number = "relative"
mouse = true
auto-save = false
text-width = 88
soft-wrap = { enable = true, wrap-at-text-width = true, wrap-indicator = "" }
rulers = [88]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "file-name", "spacer", "diagnostics"]
right = [
  "position",
  "separator",
  "spacer",
  "position-percentage",
  "spacer",
  "separator",
  "total-line-numbers",
  "separator",
  "file-line-ending",
  "separator",
  "file-type",
]

[editor.file-picker]
hidden = false

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal.space.h]
r = ":reset-diff-change"

[keys.normal.space.space]
s = ":format"
w = ":reflow"
r = ":reload"
y = [
  ':sh rm -f /var/tmp/yazi-path',
  # ":insert-output nnn %{buffer_name} -p /var/tmp/yazi-path",
  ':insert-output yazi --chooser-file=/var/tmp/yazi-path %{buffer_name}',
  ":open %sh{cat /var/tmp/yazi-path}",
  ":redraw",
  ":reload-all",
  ':set mouse false',
  ':set mouse true',
]

[keys.normal.Z]
Z = ":wq"
Q = ":q!"

[keys.normal]
D = "kill_to_line_end"
"-" = "file_picker_in_current_buffer_directory"
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
C-s = ":update"
C-e = [
  ":sh rm -f /tmp/unique-file",
  ":insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" >/dev/tty',
  ":open %sh{cat /tmp/unique-file}",
  ":redraw",
]
