[[language]]
auto-format = false
language-servers = [
  { name = "jedi-language-server" },
  { name = "ruff-lsp" },
  # { name = "ruff" },
]
name = "python"
# formatter = { command = "black", args = [ "--line-length", "88", "--quiet", "-", ] }
# formatter = { command = "ruff", args = ["format", "-"] }

[language-server.jedi-language-server]
args = []
command = "jedi-language-server"
config = {}

[language-server.ruff-lsp]
args = []
command = "ruff-lsp"
config = { settings = { args = [] } }

[[language]]
name = "latex"
text-width = 88

# [auto-pairs]
# '\'.'(' = '\)'

[language-server.texlab.config.texlab]
formatterLineLength = -1                   # bib files
latexindent = { modifyLineBreaks = false }

[language-server.texlab.config.texlab.build]
forwardSearchAfter = false
onSave = false

[language-server.texlab.config.texlab.forwardSearch]
args = ["--synctex-forward", "%l:1:%f", "%p"]
executable = "zathura"
# latexmk does something much more complicated that actually works
# args = [ "-x", "nvim", "--headless", "-c", '"VimtexInverseSearch ½{line} '%{input}'"', "--synctex-forward", "%l:1:%f", "%p"]

[language-server.texlab.config.texlab.chktex]
onEdit = true
onOpenAndSave = true

[language-server.texlab.config.texlab.experimental]
citationCommands = ["citeA"]
followPackageLinks = true
labelReferenceCommands = ["subref"]
mathEnvironments = ["align*", "equation"]

[[language]]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
name = "markdown"

[[language]]
auto-format = false
name = "go"

# # introduce new language server
# [language-server.scls]
# command = "simple-completion-language-server"

# [language-server.scls.config]
# max_completion_items = 20 # set max completion results len for each group: words, snippets, unicode-input
# snippets_first = true # completions will return before snippets by default
# feature_words = true # enable completion by word
# feature_snippets = true # enable snippets
# feature_unicode_input = true # enable "unicode input"
# feature_paths = true # enable path completion

# # write logs to /tmp/completion.log
# [language-server.scls.environment]
# RUST_LOG = "info,simple-completion-langauge-server=info"
# LOG_FILE = "/tmp/completion.log"

# append langage server to existed languages
[[language]]
language-servers = [
  # "scls",
  "rust-analyzer",
]
name = "rust"

# [[language]]
# name = "git-commit"
# language-servers = ["scls"]

[[language]]
language-servers = [
  # "scls",
  "texlab",
]
name = "latex"

# etc..

# introduce a new language to enable completion on any doc by forcing set language with :set-language stub
[[language]]
auto-format = false
file-types = []
name = "stub"
roots = []
scope = "text.stub"
shebangs = []
# language-servers = ["scls"]
