# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$sudo\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$cmake\
$cobol\
$conda\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$mise\
$nim\
$nix_shell\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$red\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$typst\
$vagrant\
$vlang\
$zig\
$package\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$cmd_duration\
$fill\
$os\
$shell\
$username\
$localip\
$hostname\
$time\
$line_break\
$jobs\
$battery\
$status\
$character"""

[profiles]
transient = """
$character\
"""

rtransient = ""

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "blue"
symbol = "☁️ "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[battery]
charging_symbol = "⚡️"
discharging_symbol = "💀"
full_symbol = "🔋"

[[battery.display]]
style = "#fa4934"
threshold = 10

[character]
error_symbol = "[\\$](#fa4934)"
success_symbol = "[\\$](#b7ba26)"
vimcmd_symbol = "[](#8dbf7c)"

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
style = "#8dbf7b"
truncation_length = 8
truncation_symbol = "…/"

[fill]
style = "dimmed #a49681"
symbol = " ~"

[git_branch]
style = "#bd7b8d"

[git_commit]
only_detached = false
tag_disabled = false

[git_metrics]
added_style = "green"
deleted_style = "red"
disabled = false

[hostname]
disabled = false
format = " @ [SSH:](red)[$hostname]($style)"
ssh_only = true
style = "dimmed #458487"
trim_at = "."

[localip]
disabled = false
format = ' is[ $localipv4]($style) '
ssh_only = false

[nodejs]
style = "#b7ba26"

[os]
disabled = false
format = " [on $symbol]($style)"
style = "blue"
[os.symbols]
Arch = "󰣇"
Debian = ""
Fedora = ""
Linux = ""
Macos = ""
NixOS = "❄️"
Raspbian = ""
RedHatEnterprise = ""
Redhat = ""
Ubuntu = ""

[package]
format = '[$symbol$version]($style) '

[python]
style = "#f5f92f"
symbol = " "

[shell]
disabled = false
format = " [with $indicator]($style)"
style = "blue"

[status]
disabled = false
map_symbol = true
not_executable_symbol = " "
not_found_symbol = " "
pipestatus = true
sigint_symbol = " "
symbol = " "

[sudo]
disabled = false
format = "[$symbol$output]($style) "
style = "fg:bright-red"
symbol = "!"

[time]
disabled = false
format = '[$time]($style)'
style = "#a49681"
time_format = "%d%b%y, %H:%M:%S(%z)"

[username]
disabled = false
format = " [$user]($style)"
show_always = true
style_root = "black"
style_user = "#e9d9b0"
