#!/usr/bin/env bash

# I install crudini using mise, so lets add the shims to path!
export PATH="$HOME/.local/share/mise/shims:$PATH"
## If picom.conf does not exist, raise an alert
[[ ! -f ~/.config/picom/picom.conf ]] \
    && notify-send "picom.conf does not exist" && exit 0

## If crudini does not exist, raise an alert
if ! command -v crudini >/dev/null 2>&1; then
    notify-send "crudini does not exist" && exit 0
fi
## Fetch background_opacity from alacritty.yml
opacity="$(crudini --get ~/.config/picom/picom.conf "" active-opacity)"
inopacity="$(crudini --get ~/.config/picom/picom.conf "" inactive-opacity)"

if [ $# -eq 0 ]; then
    echo "need an argument: u to increase opacity; d to decrease; number 0-1.0 to specific opacity"
    exit 0
elif [ "$1" == '+active' ]; then
    new=$(echo "$opacity" 0.05 | awk '{print $1 + $2}')
    if (($(echo "$new > 1.0" | bc -l))); then
        new=1
    fi
    crudini --set ~/.config/picom/picom.conf "" active-opacity "$new"
elif [ "$1" == '-active' ]; then
    new=$(echo "$opacity" 0.05 | awk '{print $1 - $2}')
    if (($(echo "$new < 0.0" | bc -l))); then
        new=0
    fi
    crudini --set ~/.config/picom/picom.conf "" active-opacity "$new"
elif [ "$1" == '+inactive' ]; then
    new=$(echo "$inopacity" 0.05 | awk '{print $1 + $2}')
    if (($(echo "$new > 1.0" | bc -l))); then
        new=1
    fi
    crudini --set ~/.config/picom/picom.conf "" inactive-opacity "$new"
elif [ "$1" == '-inactive' ]; then
    new=$(echo "$inopacity" 0.05 | awk '{print $1 - $2}')
    if (($(echo "$new < 0.0" | bc -l))); then
        new=0
    fi
    crudini --set ~/.config/picom/picom.conf "" inactive-opacity "$new"
elif (($(echo "$1 < 1.0" | bc -l))); then
    new=$1
    crudini --set ~/.config/picom/picom.conf "" inactive-opacity "$new"
elif [[ $1 == '1' ]]; then
    new=$1
    crudini --set ~/.config/picom/picom.conf "" inactive-opacity "$new"
fi

# For some reason, when nvim is open, the alacritty opacity is taking precedence, even
# though alacritty otherwise has the same opacity as that given in `picom.conf`.
# Strange! But we just update it here so its fine.

# If toml does not exist, raise an alert
if ! command -v toml >/dev/null 2>&1; then
    notify-send "toml-cli does not exist" && exit 0
fi
# toml set --toml-path ~/.config/alacritty/alacritty.toml --to-float window.opacity "$new"
