#!/bin/bash

#
# Check out this repo for how to dynamically change desktops and possibly also handle dual
# monitor setup.
# https://gitlab.com/protesilaos/dotfiles/-/tree/4363c3bf0b8e9c1dc10f1344993277cc7eaca178
#

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.config/Xresources
getcolors () {
    FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
    BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
    # BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
    RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
    # GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
    # YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
    BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
    # MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
    # CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
    # WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations -------------------------------#

if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
    bspc monitor "$(bspc query -M | sed -n 1p)" -d 1 2 3
    bspc monitor "$(bspc query -M | sed -n 2p)" -d 4 5 6
    bspc monitor "$(bspc query -M | sed -n 3p)" -d 7 8 9 0
elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
    bspc monitor eDP-1 -d 1
    if [ "$(bspc query -M --names | sed -n 1p)" = "eDP-1" ]; then
        bspc monitor "$(bspc query -M --names | sed -n 2p)" -d 2 3 4 5 6 7 8 9 0
    else
        bspc monitor ^2 -s ^1
        bspc monitor "$(bspc query -M --names | sed -n 2p)" -d 2 3 4 5 6 7 8 9 0
    fi
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Run autorandr and other workspaces things
autorandr -c
bash "$HOME/.config/bspwm/bin/bspwm_workspces.sh" &

bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.50

# bspc config focused_border_color "$BLUE"
# bspc config normal_border_color "$BACKGROUND"
# bspc config active_border_color "$MAGENTA"
# bspc config urgent_border_color "$RED"
# bspc config presel_feedback_color "$GREEN"

# Customization from https://draculatheme.com/bspwm
bspc config focused_border_color "#3CB371"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config urgent_border_color "#b4415a"
bspc config presel_feedback_color "#6272a4"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor	true
bspc config external_rules_command "$(which external_rules)"


## Window rules -------------------------------#
# Use xprop to find info about a window

# remove all rules first
bspc rule -r -- *:*

# 1 > terminal
# bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^4' follow=off focus=on

# 10 > slack
bspc rule -a Slack desktop='^10' follow=on focus=on

# 7 > office
declare -a office=(Geany Gucharmap Evince sioyek \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^7' follow=off focus=on; done

# # 5 > media
# declare -a media=(Audacity mpv mplayer lxmusic Gimp Gimp-2.8)
# for i in ${media[@]}; do
#    bspc rule -a $i desktop='^5' follow=on focus=on; done

# # 6 > settings
# bspc rule -a GParted desktop='^6' follow=on focus=on
# declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
# System-config-printer.py Pavucontrol Exo-helper-1)
# for i in ${settings[@]}; do
#    bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# special rules
# bspc rule -a alacritty-float state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a firefox locked=on
# bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a matplotlib state=floating  # rectangle=1000x700+500+500
bspc rule -a Matplotlib state=floating  # rectangle=1000x700+500+500
bspc rule -a feh state=floating  # rectangle=1000x700+500+500
bspc rule -a Zathura state=tiled
bspc rule -a Blueman-manager state=floating  # rectangle=1000x700+500+500
bspc rule -a Nm-connection-editor state=floating follow=on focus=on
bspc rule -a Alacritty:*:mylauncher state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
# bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Polybar layer=above
bspc rule -a polybar layer=above

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Hack iCursive 12" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
# Enable fast keys
xset r rate 210 40 &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
# bash $HOME/.fehbg

# Start mpd
exec mpd &

# Start bspswallow
pgrep bspswallow || bspswallow &

# Start bspwm scripts
bspcolors
bspcomp
# bspbar
sleep 2
bash "$HOME/polybar-collection/launch.sh"
# bspfloat &

## Adjust backlight (AMD)
blight -d amdgpu_bl0 set 95%

# Set wallpaper
feh --bg-fill --geometry -200 "$HOME/.cache/bspwm/wallpaper.jpg"
