#!/bin/sh

# Automatically set the splits and info
%{{
    w=$(tput cols)
    if [ $w -le 120 ]; then
        lf -remote "send $id set ratios 1:2"
        lf -remote "send $id set info"
    elif [ $w -le 200 ]; then
        lf -remote "send $id set ratios 1:2:3"
        lf -remote "send $id set info size"
    else
        lf -remote "send $id set ratios 2:3:7"
        lf -remote "send $id set info size:time"
    fi
}}

# General
set icons true
set hidden true
set scrolloff 10   # integer value

# Previewer
set previewer stpv
set cleaner stpvimgclr
&stpvimg --listen $id
# set preview true
set info size

map <enter> open
map f fzf_jump
map . set hidden!
map ac recol
map x delete

# Bookmarks
# map gb cd /cluster/home/een023/.cache/nnn/bookmarks
# map bnc cd /cluster/home/een023/model/CESM/cesm2.1.3/CESM/cime/scripts
map ba1 cd /cluster/projects/nn9817k/cesm/archive
map ba2 cd /cluster/projects/nn9348k/cesm/archive
map bn1 cd /nird/projects/NS9817K/
map bn2 cd /nird/projects/NS9063K/
map bc cd /cluster/home/een023/.config
map bl cd /cluster/home/een023/model/CESM/cesm2.1.3/CESM/cime/cases
map bp cd /cluster/home/een023/.programs
map bs cd /cluster/home/een023/.local/bin
map bu cd /cluster/work/users/een023/cesm/
map bw cd /cluster/home/een023/scripts

# Commands
cmd fzf_jump ${{
  res="$(find . -maxdepth 6 | fzf --reverse --header='Jump to location')"
  if [ -f "$res" ]; then
    cmd="select"
  elif [ -d "$res" ]; then
    cmd="cd"
  fi
  lf -remote "send $id $cmd \"$res\""
}}

cmd open ${{
    case $(file --mime-type "$f" -bL) in
        text/*|application/json) $EDITOR "$fx";;
        text/*|application/xml) $EDITOR "$fx";;
        *) for f in "$fx"; do xdg-open "$f"> /dev/null 2> /dev/null & done;;
    esac
}}

cmd recol &{{
    w=$(tput cols)
    if [ $w -le 120 ]; then
        lf -remote "send $id set ratios 1:2"
        lf -remote "send $id set info"
    elif [ $w -le 200 ]; then
        lf -remote "send $id set ratios 1:2:3"
        lf -remote "send $id set info size"
    else
        lf -remote "send $id set ratios 2:3:7"
        lf -remote "send $id set info size:time"
    fi
}}
