exec-once = batsignal -b
exec-once = battery-flicker
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = shikane
exec-once = dunst -conf ~/.config/dunst/dunstrc
exec-once = swaybg -m fill -i ~/.cache/wallpaper/wallpaper.jpg
exec-once = bash ~/.config/hypr/scripts/hide_waybar.sh --set
exec-once = clipcatd
exec-once = bash -c 'echo "Xft.dpi: 140" | xrdb -merge'
exec-once = fcitx5 --replace -d
exec-once = blueman-applet
exec-once = nm-applet
exec-once = swayosd-server
