#!/bin/sh

# Makes the prompt a bit slower, but not much
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/een023/programs/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/een023/programs/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/een023/programs/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/een023/programs/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
