[mgr]
linemode = "size"
show_hidden = true
show_symlink = true
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false

[opener]
edit = [{ run = '${EDITOR:-nvim} "$@"', block = true, for = "unix" }]
feh = [{ run = 'feh --scale-down "$1"' }]
# nuke = [
#   { run = '~/.config/nnn/plugins/nuke "$1"', desc = "Open", for = "linux" },
# ]

[open]
prepend_rules = [{ mime = "image/*", use = "feh" }, { mime = "*/csv", use = "edit" }]

[preview]
max_width = 1500

[plugin]
prepend_previewers = [
  { url = "*.csv", run = "duckdb" },
  { mime = "*/csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  # { name = "*.json", run = "duckdb" },
  # { mime = "*/json", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { mime = "image/heic", run = "heic" },
  { url = "*.nc", run = 'piper -- ncdump-rich --long "$1"' },
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false },
]

[[plugin.prepend_fetchers]]
group = "git"
id = "git"
mime = "*"
run = "git"
[[plugin.prepend_fetchers]]
group = "git"
id = "git"
mime = "*/"
run = "git"
