#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# Using a lot from https://github.com/FelixKratz/dotfiles as well
# Unload the macOS WindowManager process
# launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

# refresh my Ubersicht bar when the space changes
# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application \"Übersicht\" to refresh'"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.95
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_radius         0
yabai -m config window_border_width          0
yabai -m config active_window_border_color   0xff3fc43c  # 0xff775759
yabai -m config normal_window_border_color   0x00FFFFFF  # 0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn  # cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  28 # 2
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# app specific
# System preferences
# yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Systemvalg$" manage=off
yabai -m rule --add app="^QtPass$" manage=off
# yabai -m rule --add app="^Finder$" layer=above manage=off
yabai -m rule --add app="^Plash$" layer=above manage=off
yabai -m rule --add app="^ZAthura$" layer=above manage=on
yabai -m rule --add app="^.*pner.*$" sticky=on layer=above manage=off
yabai -m rule --add title="mylauncher" manage=off sticky=on layer=above border=off

echo "yabai configuration loaded.."

