return {
  "nat-418/boole.nvim",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    mappings = {
      increment = "<C-a>",
      decrement = "<C-x>",
    },
    -- User defined loops
    additions = {
      { "Foo", "Bar" },
      { "tic", "tac", "toe" },
      { "acquire", "release" },
      { "add", "remove" },
      { "advance", "retreat" },
      { "allocate", "deallocate" },
      { "allow", "deny" },
      { "assemble", "disassemble" },
      { "assign", "deassign" },
      { "associate", "dissociate" },
      { "attach", "detach" },
      { "begin", "end" },
      { "bind", "unbind" },
      { "commit", "rollback" },
      { "compile", "decompile" },
      { "compose", "parse" },
      { "compress", "decompress" },
      { "connect", "disconnect" },
      { "construct", "destruct" },
      { "create", "destroy" },
      { "do", "undo" },
      { "enable", "disable" },
      { "encode", "decode" },
      { "encrypt", "decrypt" },
      { "enqueue", "dequeue" },
      { "enter", "leave" },
      { "expand", "collapse" },
      { "first", "last" },
      { "freeze", "unfreeze" },
      { "front", "back" },
      { "get", "set" },
      { "grant", "revoke" },
      { "head", "tail" },
      { "high", "low" },
      { "import", "export" },
      { "include", "exclude" },
      { "increase", "decrease" },
      { "increment", "decrement" },
      { "indent", "dedent" },
      { "inflate", "deflate" },
      { "inject", "eject" },
      { "input", "output" },
      { "insert", "delete" },
      { "install", "uninstall" },
      { "left", "right" },
      { "Left", "Right" },
      { "link", "unlink" },
      { "load", "unload" },
      { "lock", "unlock" },
      { "maximum", "minimum" },
      { "new", "old" },
      { "next", "previous", "prev" },
      { "open", "close" },
      { "on", "off" },
      { "paste", "cut", "yank" },
      { "push", "pop" },
      { "read", "write" },
      { "real", "fake" },
      { "reference", "dereference" },
      { "register", "deregister" },
      { "resume", "suspend" },
      { "select", "deselect" },
      { "send", "receive" },
      { "serialize", "deserialize" },
      { "set", "unset" },
      { "show", "hide" },
      { "start", "stop" },
      { "true", "false" },
      { "True", "False" },
      { "TRUE", "FALSE" },
      { "1", "0" },
      { "yes", "no" },
      { "Yes", "No" },
      { "YES", "NO" },
      { "up", "down" },
      { "Up", "Down" },
      { "upper", "lower" },
      {
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
      },
      {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
      },
      {
        "alpha",
        "beta",
        "gamma",
        "delta",
        "epsilon",
        "zeta",
        "eta",
        "theta",
        "iota",
        "kappa",
        "lambda",
        "mu",
        "nu",
        "xi",
        "omicron",
        "pi",
        "rho",
        "sigma",
        "tau",
        "upsilon",
        "phi",
        "chi",
        "psi",
        "omega",
      },
      {
        "Alpha",
        "Beta",
        "Gamma",
        "Delta",
        "Epsilon",
        "Zeta",
        "Eta",
        "Theta",
        "Iota",
        "Kappa",
        "Lambda",
        "Mu",
        "Nu",
        "Xi",
        "Omicron",
        "Pi",
        "Rho",
        "Sigma",
        "Tau",
        "Upsilon",
        "Phi",
        "Chi",
        "Psi",
        "Omega",
      },
      {
        "ALPHA",
        "BETA",
        "GAMMA",
        "DELTA",
        "EPSILON",
        "ZETA",
        "ETA",
        "THETA",
        "IOTA",
        "KAPPA",
        "LAMBDA",
        "MU",
        "NU",
        "XI",
        "OMICRON",
        "PI",
        "RHO",
        "SIGMA",
        "TAU",
        "UPSILON",
        "PHI",
        "CHI",
        "PSI",
        "OMEGA",
      },
      { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" },
      {
        "zero",
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
      },
      {
        "Zero",
        "One",
        "Two",
        "Three",
        "Four",
        "Five",
        "Six",
        "Seven",
        "Eight",
        "Nine",
      },
    },
  },
}
