"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[transient_prompt]
background = "transparent"
foreground_templates = ["{{ if gt .Code 0 }}#e91e63{{ end }}"]
template = "{{if .Root}} # {{else}} $ {{end}}"

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
type = "root"
style = "plain"
foreground = "#b41818"
template = " "

[[blocks.segments]]
foreground = "#61AFEF"
# exclude_folders = ["/super/secret/project"]
template = '{{if .Segments.Git}}../{{ .Format .Segments.Git.RepoName }}{{if matchP ".+" .Segments.Git.RelativeDir}}/{{ .Format .Segments.Git.RelativeDir }}{{else}}{{end}}{{else}}{{.Path}}{{end}}'
style = "plain"
type = "path"

[blocks.segments.properties]
style = "powerlevel"

[[blocks.segments]]
foreground = "#af7de8"
style = "plain"
type = "git"

[blocks.segments.properties]
branch_template = "{{ trunc 25 .Branch }}"
fetch_status = true

[[blocks.segments]]
type = "python"
style = "plain"
foreground = "#ebeb47"
template = "{{ if .Error }}{{ .Error }}{{ else }}  {{ .Full }}{{ if .Venv }}({{ .Venv }}){{ end }}{{ end }}"

[[blocks.segments]]
type = "go"
style = "plain"

[[blocks.segments]]
type = "lua"
style = "plain"

[[blocks.segments]]
type = "rust"
style = "plain"

[[blocks.segments]]
type = "node"
style = "plain"

[[blocks.segments]]
type = "zig"
style = "plain"

[[blocks.segments]]
type = "project"
style = "plain"
# template = "  {{ .MajorMinorPatch }} "

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "#8800dd"
template = " took {{ .FormattedMs }} "

[blocks.segments.properties]
threshold = 500
style = "round"

[[blocks]]
alignment = "right"
newline = false
type = "prompt"
# filler = " ~"
overflow = "hide"
filler = "{{ if .Overflow }} {{ else }} <#4d4d4d>~</>{{ end }}"
foreground = "#4d4d4d"

[[blocks.segments]]
type = "battery"
style = "plain"
foreground = "#b8142a"
template = " {{ if not .Error }}{{ if le .Percentage 20 }}{{ .Icon }}<b>{{ .Percentage }}</b>{{end}}{{ end }}"

[blocks.segments.properties]
discharging_icon = " "
charging_icon = " "
charged_icon = " "
not_charging_icon = "󰂂 "

[[blocks.segments]]
style = "plain"
type = "session"
template = " <d>[{{.UserName}} @ {{.HostName}}</d>"

[[blocks.segments]]
type = "os"
style = "plain"
template = "<d> on {{ if .WSL }}WSL at {{ end }}{{.Icon}} ]</d>"

[[blocks.segments]]
template = ' <d>{{ .CurrentDate | date .Format }}</d>'
style = "plain"
type = "time"

[blocks.segments.properties]
time_format = "02Jan06, 15:04:05(-0700)"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "#2e466b"
template = "{{if gt .Jobs 0}}{{ .Jobs }}{{else}} {{end}}"

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = ["{{ if gt .Code 0 }}#e91e63{{ end }}"]
template = "{{if .Root}} # {{else}} $ {{end}}"
