"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[transient_prompt]
background = "transparent"
foreground_templates = ["{{ if gt .Code 0 }}#e91e63{{ end }}"]
template = "{{if .Root}} # {{else}} $ {{end}}"

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
foreground = "#b41818"
style = "plain"
template = " "
type = "root"

[[blocks.segments]]
foreground = "#61AFEF"
# exclude_folders = ["/super/secret/project"]
style = "plain"
template = '{{if .Segments.Git}}../{{ .Format .Segments.Git.RepoName }}{{if matchP ".+" .Segments.Git.RelativeDir}}/{{ .Format .Segments.Git.RelativeDir }}{{else}}{{end}}{{else}}{{.Path}}{{end}}'
type = "path"

[blocks.segments.properties]
style = "powerlevel"

[[blocks.segments]]
foreground = "#af7de8"
style = "plain"
type = "git"

[blocks.segments.properties]
branch_template = "{{ trunc 25 .Branch }}"
fetch_status = true

[[blocks.segments]]
foreground = "#ebeb47"
style = "plain"
template = "{{ if .Error }}{{ .Error }}{{ else }}  {{ .Full }}{{ if .Venv }}({{ .Venv }}){{ end }}{{ end }}"
type = "python"

[[blocks.segments]]
style = "plain"
type = "go"

[[blocks.segments]]
style = "plain"
type = "lua"

[[blocks.segments]]
style = "plain"
type = "rust"

[[blocks.segments]]
style = "plain"
type = "node"

[[blocks.segments]]
style = "plain"
type = "zig"

[[blocks.segments]]
style = "plain"
type = "project"
# template = "  {{ .MajorMinorPatch }} "

[[blocks.segments]]
foreground = "#8800dd"
style = "plain"
template = " took {{ .FormattedMs }} "
type = "executiontime"

[blocks.segments.properties]
style = "round"
threshold = 500

[[blocks]]
alignment = "right"
newline = false
type = "prompt"
# filler = " ~"
filler = "{{ if .Overflow }} {{ else }} <#4d4d4d>~</>{{ end }}"
foreground = "#4d4d4d"
overflow = "hide"

[[blocks.segments]]
foreground = "#b8142a"
style = "plain"
template = " {{ if not .Error }}{{ if le .Percentage 20 }}{{ .Icon }}<b>{{ .Percentage }}</b>{{end}}{{ end }}"
type = "battery"

[blocks.segments.properties]
charged_icon = " "
charging_icon = " "
discharging_icon = " "
not_charging_icon = "󰂂 "

[[blocks.segments]]
style = "plain"
template = " <d>[{{.UserName}} @ {{.HostName}}</d>"
type = "session"

[[blocks.segments]]
style = "plain"
template = "<d> on {{ if .WSL }}WSL at {{ end }}{{.Icon}} ]</d>"
type = "os"

[[blocks.segments]]
style = "plain"
template = ' <d>{{ .CurrentDate | date .Format }}</d>'
type = "time"

[blocks.segments.properties]
time_format = "02Jan06, 15:04:05(-0700)"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#2e466b"
style = "plain"
template = "{{if gt .Jobs 0}}{{ .Jobs }}{{else}} {{end}}"
type = "text"

[[blocks.segments]]
foreground_templates = ["{{ if gt .Code 0 }}#e91e63{{ end }}"]
style = "plain"
template = "{{if .Root}} # {{else}} $ {{end}}"
type = "text"
