#!/usr/bin/env bash

# I install toml (toml-cli) using mise, so lets add the shims to path!
export PATH="$HOME/.local/share/mise/shims:$PATH"
## If alacritty.toml does not exist, raise an alert
[[ ! -f ~/.config/alacritty/alacritty.toml ]] \
    && dunst "alacritty.toml does not exist" && exit 0

## If toml does not exist, raise an alert
if ! command -v toml >/dev/null 2>&1; then
    notify-send "toml-cli does not exist" && exit 0
fi
## Fetch background_opacity from alacritty.yml
opacity="$(toml get --toml-path ~/.config/alacritty/alacritty.toml window.opacity)"

if [ $# -eq 0 ]; then
    echo "need an argument: u for increase opacity d to decrease number 0-1.0 to specific opacity"
    new="$opacity"
elif [ "$1" == 'u' ]; then
    new=$(echo "$opacity" 0.05 | awk '{print $1 + $2}')
    if (($(echo "$new > 1.0" | bc -l))); then
        echo "Variable is greater than 1.0"
        new=1
    fi
elif [ "$1" == 'd' ]; then
    new=$(echo "$opacity" 0.05 | awk '{print $1 - $2}')
    if (($(echo "$new < 0.0" | bc -l))); then
        new=0
    fi
elif (($(echo "$1 < 1.0" | bc -l))); then
    new=$1
elif [[ $1 == '1' ]]; then
    new=$1
else
    new="$opacity"
fi

## Replace opacity value in alacritty.yml
toml set --toml-path ~/.config/alacritty/alacritty.toml --to-float window.opacity "$new"
